backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "src/images"
public_folder: "/images"
collections:
  - name: "lighthouse"
  label: "lighthouse"
  folder: "src"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  fields:
    - {labels: "title", name: "title", widget: "string"}
    - {labels: "Image", name: "image", widget: "image"}
    - {labels: "Image caption", name: "imageAlt", widget: "string"}
    - {labels: "Tags", name: "tags", widget: "list", default:["post"]}
    - {labels: "body", name: "body", widget: "markdown"}


